version: '3.8'

services:
  # Base de Datos Oracle XE
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1523:1521"  # Tu gestor de BD (DBeaver/SQL Developer) se conectará por el 1522
    environment:
      - ORACLE_PASSWORD=admin
      - APP_USER=system
      - APP_USER_PASSWORD=admin
    networks:
      - shop-network

  # Microservicio de Usuarios (Puerto 8085)
  ms-usuarios:
    image: shopconnect/ms-usuarios:0.0.1
    container_name: ms-usuarios
    ports:
      - "8085:8085"
    depends_on:
      - oracle-db
    networks:
      - shop-network

  # Microservicio de Productos (Puerto 8081)
  ms-productos:
    image: shopconnect/ms-productos:0.0.1
    container_name: ms-productos
    ports:
      - "8081:8081"
    depends_on:
      - oracle-db
    networks:
      - shop-network

  # Microservicio de Inventario (Puerto 8082)
  ms-inventario:
    image: shopconnect/ms-inventario:0.0.1
    container_name: ms-inventario
    ports:
      - "8082:8082"
    depends_on:
      - oracle-db
    networks:
      - shop-network

  # Microservicio de Pedidos (Puerto 8083)
  ms-pedidos:
    image: shopconnect/ms-pedidos:0.0.1
    container_name: ms-pedidos
    ports:
      - "8083:8083"
    depends_on:
      - oracle-db
    networks:
      - shop-network

  # Microservicio de Pagos (Puerto 8084)
  ms-pagos:
    image: shopconnect/ms-pagos:0.0.1
    container_name: ms-pagos
    ports:
      - "8084:8084"
    depends_on:
      - oracle-db
    networks:
      - shop-network

# Red interna de Docker
networks:
  shop-network:
    driver: bridge