services:
  # 1. El motor de la base de datos
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=admin
    networks:
      - shop-network

  # 2. Microservicio de Pedidos
  ms-pedidos:
    build: ./ms-pedidos
    container_name: ms-pedidos
    ports:
      - "8083:8083"
    depends_on:
      - oracle-db
    networks:
      - shop-network

  # 3. Microservicio de Inventario
  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    ports:
      - "8084:8084"
    depends_on:
      - oracle-db
    networks:
      - shop-network

  # 4. Microservicio de Usuarios
  ms-usuarios:
    build: ./ms-usuarios
    container_name: ms-usuarios
    ports:
      - "8082:8082"
    depends_on:
      - oracle-db
    networks:
      - shop-network

  # 5. Microservicio de Pagos
  ms-pagos:
    build: ./ms-pagos
    container_name: ms-pagos
    ports:
      - "8085:8085"
    depends_on:
      - oracle-db
    networks:
      - shop-network

  # 6. Microservicio de Productos
  ms-productos:
    build: ./ms-productos
    container_name: ms-productos
    ports:
      - "8081:8081"
    depends_on:
      - oracle-db
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge