server.port=8083
spring.application.name=ms-pedidos

# Usamos localhost porque el microservicio está fuera de Docker
spring.datasource.url=jdbc:oracle:thin:@oracle-db:1521:XE
spring.datasource.username=system
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- CONFIGURACIÓN DE ESTABILIDAD ---
# Fuerza el dialecto antes de intentar conectarcd 
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Evita que el microservicio se apague si Oracle tarda en arrancar
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
